import type { Job } from "./types";

export const jobs: Job[] = [
  {
    job_id: "JOB-0001",
    employer_logo: "https://logo.clearbit.com/google.com",
    employer_name: "Google",
    job_title: "Frontend Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$140k - $180k",
    job_description:
      "Build and optimize user interfaces using React and TypeScript for high-traffic web apps.",
  },
  {
    job_id: "JOB-0002",
    employer_logo: "https://logo.clearbit.com/meta.com",
    employer_name: "Meta",
    job_title: "Machine Learning Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$160k - $220k",
    job_description:
      "Design and deploy ML models at scale, collaborating with product and infra teams.",
  },
  {
    job_id: "JOB-0003",
    employer_logo: "https://logo.clearbit.com/amazon.com",
    employer_name: "Amazon",
    job_title: "Backend Engineer",
    job_employment_type: "Full time",
    job_location: "Canada",
    job_salary: "$130k - $170k",
    job_description:
      "Develop distributed services in Node.js and Java powering marketplace features.",
  },
  {
    job_id: "JOB-0004",
    employer_logo: "https://logo.clearbit.com/microsoft.com",
    employer_name: "Microsoft",
    job_title: "Full Stack Developer",
    job_employment_type: "Contract",
    job_location: "Remote",
    job_salary: "$80 - $110/hr",
    job_description:
      "Ship end-to-end features across React frontends and .NET backends.",
  },
  {
    job_id: "JOB-0005",
    employer_logo: "https://logo.clearbit.com/stripe.com",
    employer_name: "Stripe",
    job_title: "API Engineer",
    job_employment_type: "Full time",
    job_location: "Ireland",
    job_salary: "€95k - €130k",
    job_description:
      "Design reliable, well-documented APIs and improve developer experience.",
  },
  {
    job_id: "JOB-0006",
    employer_logo: "https://logo.clearbit.com/airbnb.com",
    employer_name: "Airbnb",
    job_title: "iOS Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$150k - $200k",
    job_description:
      "Build delightful native experiences with Swift and UIKit/SwiftUI.",
  },
  {
    job_id: "JOB-0007",
    employer_logo: "https://logo.clearbit.com/netflix.com",
    employer_name: "Netflix",
    job_title: "UI Engineer",
    job_employment_type: "Contract",
    job_location: "Remote",
    job_salary: "$100 - $140/hr",
    job_description:
      "Prototype and productionize complex UI flows across TV and mobile platforms.",
  },
  {
    job_id: "JOB-0008",
    employer_logo: "https://logo.clearbit.com/uber.com",
    employer_name: "Uber",
    job_title: "Android Engineer",
    job_employment_type: "Full time",
    job_location: "India",
    job_salary: "₹30L - ₹60L",
    job_description:
      "Develop high-performance Android features with Kotlin and Jetpack.",
  },
  {
    job_id: "JOB-0009",
    employer_logo: "https://logo.clearbit.com/spotify.com",
    employer_name: "Spotify",
    job_title: "Data Engineer",
    job_employment_type: "Full time",
    job_location: "Sweden",
    job_salary: "SEK 650k - 900k",
    job_description:
      "Build robust data pipelines and analytics platforms using Scala and Python.",
  },
  {
    job_id: "JOB-0010",
    employer_logo: "https://logo.clearbit.com/shopify.com",
    employer_name: "Shopify",
    job_title: "Rails Developer",
    job_employment_type: "Full time",
    job_location: "Canada",
    job_salary: "$120k - $160k",
    job_description:
      "Enhance core commerce features across Ruby on Rails services.",
  },
  {
    job_id: "JOB-0011",
    employer_logo: "https://logo.clearbit.com/adobe.com",
    employer_name: "Adobe",
    job_title: "TypeScript Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$135k - $175k",
    job_description:
      "Build reusable component libraries and tooling with TypeScript.",
  },
  {
    job_id: "JOB-0012",
    employer_logo: "https://logo.clearbit.com/twilio.com",
    employer_name: "Twilio",
    job_title: "DevOps Engineer",
    job_employment_type: "Full time",
    job_location: "United Kingdom",
    job_salary: "£80k - £110k",
    job_description:
      "Automate CI/CD pipelines, observability, and cloud infra with Terraform.",
  },
  {
    job_id: "JOB-0013",
    employer_logo: "https://logo.clearbit.com/palantir.com",
    employer_name: "Palantir",
    job_title: "Platform Engineer",
    job_employment_type: "Full time",
    job_location: "Germany",
    job_salary: "€85k - €120k",
    job_description:
      "Build secure, scalable platforms enabling data apps for enterprise clients.",
  },
  {
    job_id: "JOB-0014",
    employer_logo: "https://logo.clearbit.com/asana.com",
    employer_name: "Asana",
    job_title: "Product Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$140k - $185k",
    job_description:
      "Own product surfaces end-to-end, from design to implementation.",
  },
  {
    job_id: "JOB-0015",
    employer_logo: "https://logo.clearbit.com/slack.com",
    employer_name: "Slack",
    job_title: "React Native Engineer",
    job_employment_type: "Full time",
    job_location: "Remote",
    job_salary: "$140k - $180k",
    job_description:
      "Deliver cross-platform mobile features with React Native and TypeScript.",
  },
  {
    job_id: "JOB-0016",
    employer_logo: "https://logo.clearbit.com/atlassian.com",
    employer_name: "Atlassian",
    job_title: "SRE",
    job_employment_type: "Full time",
    job_location: "Australia",
    job_salary: "A$140k - A$190k",
    job_description:
      "Improve reliability, scalability, and incident response across cloud products.",
  },
  {
    job_id: "JOB-0017",
    employer_logo: "https://logo.clearbit.com/figma.com",
    employer_name: "Figma",
    job_title: "Performance Engineer",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$150k - $200k",
    job_description:
      "Profile and optimize rendering and memory usage in complex web apps.",
  },
  {
    job_id: "JOB-0018",
    employer_logo: "https://logo.clearbit.com/coursera.org",
    employer_name: "Coursera",
    job_title: "QA Engineer",
    job_employment_type: "Contract",
    job_location: "Remote",
    job_salary: "$70 - $90/hr",
    job_description:
      "Create automated test suites and ensure release quality across services.",
  },
  {
    job_id: "JOB-0019",
    employer_logo: "https://logo.clearbit.com/duolingo.com",
    employer_name: "Duolingo",
    job_title: "Data Scientist",
    job_employment_type: "Full time",
    job_location: "United States",
    job_salary: "$140k - $180k",
    job_description:
      "Run experiments, analyze product metrics, and influence roadmap decisions.",
  },
  {
    job_id: "JOB-0020",
    employer_logo: "https://logo.clearbit.com/openai.com",
    employer_name: "OpenAI",
    job_title: "Research Engineer",
    job_employment_type: "Full time",
    job_location: "Remote",
    job_salary: "$180k - $300k",
    job_description:
      "Prototype and productionize cutting-edge AI systems with robust safety tooling.",
  },
  {
    job_id: "JOB-0021",
    employer_logo: "https://logo.clearbit.com/nintendo.com",
    employer_name: "Nintendo",
    job_title: "Gameplay Developer (Intern)",
    job_employment_type: "Intern",
    job_location: "Japan",
    job_salary: "¥250k - ¥400k",
    job_description:
      "Assist in prototyping and building game mechanics with C++ and Unity.",
  },
  {
    job_id: "JOB-0022",
    employer_logo: "https://logo.clearbit.com/tesla.com",
    employer_name: "Tesla",
    job_title: "Data Analyst (Part time)",
    job_employment_type: "Part time",
    job_location: "United States",
    job_salary: "$35 - $55/hr",
    job_description:
      "Analyze manufacturing data, build dashboards, and support decision-making.",
  },
  {
    job_id: "JOB-0023",
    employer_logo: "https://logo.clearbit.com/coinbase.com",
    employer_name: "Coinbase",
    job_title: "Security Engineer (Intern)",
    job_employment_type: "Intern",
    job_location: "Remote",
    job_salary: "$35 - $50/hr",
    job_description:
      "Support threat modeling and tooling to improve platform security.",
  },
  {
    job_id: "JOB-0024",
    employer_logo: "https://logo.clearbit.com/zoom.us",
    employer_name: "Zoom",
    job_title: "Frontend Developer (Part time)",
    job_employment_type: "Part time",
    job_location: "Remote",
    job_salary: "$45 - $70/hr",
    job_description:
      "Implement UI components and performance improvements for web apps.",
  },
  {
    job_id: "JOB-0025",
    employer_logo: "https://logo.clearbit.com/squareup.com",
    employer_name: "Block (Square)",
    job_title: "Mobile QA (Intern)",
    job_employment_type: "Intern",
    job_location: "United States",
    job_salary: "$30 - $45/hr",
    job_description:
      "Author test plans, automate mobile test cases, and run regression suites.",
  },
  {
    job_id: "JOB-0026",
    employer_logo: "https://logo.clearbit.com/lyft.com",
    employer_name: "Lyft",
    job_title: "Backend Developer (Part time)",
    job_employment_type: "Part time",
    job_location: "Canada",
    job_salary: "$50 - $80/hr",
    job_description:
      "Build and maintain microservices in Go, focusing on reliability.",
  },
  {
    job_id: "JOB-0027",
    employer_logo: "https://logo.clearbit.com/snap.com",
    employer_name: "Snap",
    job_title: "ML Research Intern",
    job_employment_type: "Intern",
    job_location: "United States",
    job_salary: "$35 - $55/hr",
    job_description:
      "Explore and prototype computer vision models for AR experiences.",
  },
  {
    job_id: "JOB-0028",
    employer_logo: "https://logo.clearbit.com/imdb.com",
    employer_name: "IMDb",
    job_title: "Content Tools Engineer (Part time)",
    job_employment_type: "Part time",
    job_location: "United Kingdom",
    job_salary: "£35 - £55/hr",
    job_description: "Improve internal editorial tools with React and Node.js.",
  },
  {
    job_id: "JOB-0029",
    employer_logo: "https://logo.clearbit.com/ea.com",
    employer_name: "EA Games",
    job_title: "Build Systems Intern",
    job_employment_type: "Intern",
    job_location: "Canada",
    job_salary: "$28 - $40/hr",
    job_description:
      "Help maintain CI/CD pipelines and improve developer tooling.",
  },
  {
    job_id: "JOB-0030",
    employer_logo: "https://logo.clearbit.com/reddit.com",
    employer_name: "Reddit",
    job_title: "React Developer (Part time)",
    job_employment_type: "Part time",
    job_location: "Remote",
    job_salary: "$45 - $75/hr",
    job_description:
      "Deliver features and performance optimizations across community surfaces.",
  },
];
